//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.GPSData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="GPSData.GPS_DataSoap")]
    public interface GPS_DataSoap {
        
        // CODEGEN: Generating message contract since element name GetCarPositionResult from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/GetCarPosition", ReplyAction="*")]
        Final_Project.GPSData.GetCarPositionResponse GetCarPosition(Final_Project.GPSData.GetCarPositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/GetCarPosition", ReplyAction="*")]
        System.Threading.Tasks.Task<Final_Project.GPSData.GetCarPositionResponse> GetCarPositionAsync(Final_Project.GPSData.GetCarPositionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarPositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarPosition", Namespace="http://localhost/", Order=0)]
        public Final_Project.GPSData.GetCarPositionRequestBody Body;
        
        public GetCarPositionRequest() {
        }
        
        public GetCarPositionRequest(Final_Project.GPSData.GetCarPositionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetCarPositionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CarNum;
        
        public GetCarPositionRequestBody() {
        }
        
        public GetCarPositionRequestBody(int CarNum) {
            this.CarNum = CarNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarPositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarPositionResponse", Namespace="http://localhost/", Order=0)]
        public Final_Project.GPSData.GetCarPositionResponseBody Body;
        
        public GetCarPositionResponse() {
        }
        
        public GetCarPositionResponse(Final_Project.GPSData.GetCarPositionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetCarPositionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCarPositionResult;
        
        public GetCarPositionResponseBody() {
        }
        
        public GetCarPositionResponseBody(string GetCarPositionResult) {
            this.GetCarPositionResult = GetCarPositionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GPS_DataSoapChannel : Final_Project.GPSData.GPS_DataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPS_DataSoapClient : System.ServiceModel.ClientBase<Final_Project.GPSData.GPS_DataSoap>, Final_Project.GPSData.GPS_DataSoap {
        
        public GPS_DataSoapClient() {
        }
        
        public GPS_DataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPS_DataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPS_DataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPS_DataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Final_Project.GPSData.GetCarPositionResponse Final_Project.GPSData.GPS_DataSoap.GetCarPosition(Final_Project.GPSData.GetCarPositionRequest request) {
            return base.Channel.GetCarPosition(request);
        }
        
        public string GetCarPosition(int CarNum) {
            Final_Project.GPSData.GetCarPositionRequest inValue = new Final_Project.GPSData.GetCarPositionRequest();
            inValue.Body = new Final_Project.GPSData.GetCarPositionRequestBody();
            inValue.Body.CarNum = CarNum;
            Final_Project.GPSData.GetCarPositionResponse retVal = ((Final_Project.GPSData.GPS_DataSoap)(this)).GetCarPosition(inValue);
            return retVal.Body.GetCarPositionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Final_Project.GPSData.GetCarPositionResponse> Final_Project.GPSData.GPS_DataSoap.GetCarPositionAsync(Final_Project.GPSData.GetCarPositionRequest request) {
            return base.Channel.GetCarPositionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Final_Project.GPSData.GetCarPositionResponse> GetCarPositionAsync(int CarNum) {
            Final_Project.GPSData.GetCarPositionRequest inValue = new Final_Project.GPSData.GetCarPositionRequest();
            inValue.Body = new Final_Project.GPSData.GetCarPositionRequestBody();
            inValue.Body.CarNum = CarNum;
            return ((Final_Project.GPSData.GPS_DataSoap)(this)).GetCarPositionAsync(inValue);
        }
    }
}
