//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/numEntries", ReplyAction="*")]
        int numEntries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/numEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<int> numEntriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/valAt", ReplyAction="*")]
        System.Nullable<int> valAt(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/valAt", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Nullable<int>> valAtAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/setVal", ReplyAction="*")]
        System.Nullable<int> setVal(int i, int v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/setVal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Nullable<int>> setValAsync(int i, int v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/newEntry", ReplyAction="*")]
        System.Nullable<int> newEntry(int v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/newEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Nullable<int>> newEntryAsync(int v);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication27.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication27.ServiceReference1.WebService1Soap>, WebApplication27.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int numEntries() {
            return base.Channel.numEntries();
        }
        
        public System.Threading.Tasks.Task<int> numEntriesAsync() {
            return base.Channel.numEntriesAsync();
        }
        
        public System.Nullable<int> valAt(int i) {
            return base.Channel.valAt(i);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> valAtAsync(int i) {
            return base.Channel.valAtAsync(i);
        }
        
        public System.Nullable<int> setVal(int i, int v) {
            return base.Channel.setVal(i, v);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> setValAsync(int i, int v) {
            return base.Channel.setValAsync(i, v);
        }
        
        public System.Nullable<int> newEntry(int v) {
            return base.Channel.newEntry(v);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> newEntryAsync(int v) {
            return base.Channel.newEntryAsync(v);
        }
    }
}
