//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceReference1.GPS_DataSoap")]
    public interface GPS_DataSoap {
        
        // CODEGEN: Generating message contract since element name GetCarPositionResult from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/GetCarPosition", ReplyAction="*")]
        WebApplication27.ServiceReference1.GetCarPositionResponse GetCarPosition(WebApplication27.ServiceReference1.GetCarPositionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/GetCarPosition", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication27.ServiceReference1.GetCarPositionResponse> GetCarPositionAsync(WebApplication27.ServiceReference1.GetCarPositionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarPositionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarPosition", Namespace="http://localhost/", Order=0)]
        public WebApplication27.ServiceReference1.GetCarPositionRequestBody Body;
        
        public GetCarPositionRequest() {
        }
        
        public GetCarPositionRequest(WebApplication27.ServiceReference1.GetCarPositionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetCarPositionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CarNum;
        
        public GetCarPositionRequestBody() {
        }
        
        public GetCarPositionRequestBody(int CarNum) {
            this.CarNum = CarNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarPositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarPositionResponse", Namespace="http://localhost/", Order=0)]
        public WebApplication27.ServiceReference1.GetCarPositionResponseBody Body;
        
        public GetCarPositionResponse() {
        }
        
        public GetCarPositionResponse(WebApplication27.ServiceReference1.GetCarPositionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetCarPositionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCarPositionResult;
        
        public GetCarPositionResponseBody() {
        }
        
        public GetCarPositionResponseBody(string GetCarPositionResult) {
            this.GetCarPositionResult = GetCarPositionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GPS_DataSoapChannel : WebApplication27.ServiceReference1.GPS_DataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPS_DataSoapClient : System.ServiceModel.ClientBase<WebApplication27.ServiceReference1.GPS_DataSoap>, WebApplication27.ServiceReference1.GPS_DataSoap {
        
        public GPS_DataSoapClient() {
        }
        
        public GPS_DataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPS_DataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPS_DataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPS_DataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication27.ServiceReference1.GetCarPositionResponse WebApplication27.ServiceReference1.GPS_DataSoap.GetCarPosition(WebApplication27.ServiceReference1.GetCarPositionRequest request) {
            return base.Channel.GetCarPosition(request);
        }
        
        public string GetCarPosition(int CarNum) {
            WebApplication27.ServiceReference1.GetCarPositionRequest inValue = new WebApplication27.ServiceReference1.GetCarPositionRequest();
            inValue.Body = new WebApplication27.ServiceReference1.GetCarPositionRequestBody();
            inValue.Body.CarNum = CarNum;
            WebApplication27.ServiceReference1.GetCarPositionResponse retVal = ((WebApplication27.ServiceReference1.GPS_DataSoap)(this)).GetCarPosition(inValue);
            return retVal.Body.GetCarPositionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication27.ServiceReference1.GetCarPositionResponse> WebApplication27.ServiceReference1.GPS_DataSoap.GetCarPositionAsync(WebApplication27.ServiceReference1.GetCarPositionRequest request) {
            return base.Channel.GetCarPositionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication27.ServiceReference1.GetCarPositionResponse> GetCarPositionAsync(int CarNum) {
            WebApplication27.ServiceReference1.GetCarPositionRequest inValue = new WebApplication27.ServiceReference1.GetCarPositionRequest();
            inValue.Body = new WebApplication27.ServiceReference1.GetCarPositionRequestBody();
            inValue.Body.CarNum = CarNum;
            return ((WebApplication27.ServiceReference1.GPS_DataSoap)(this)).GetCarPositionAsync(inValue);
        }
    }
}
